### ISSUE TITLE
[Feature Request] Show git repo's folder name instead of VS Code's workspace folder name

### ISSUE THREAD

**Issue by zeroxia** [koalamer/vsc-workspace-in-status-bar#1]
I hope VS Code's "source control" on status bar could also display a "workspace name" alongside the "git branch".

This extension is close, but not exactly I want.

I think this could be common:

A git repo is like this:

`/some/path/to/my_repo_1/.git/`

And the actual workspace is a sub-directory inside it:

`/some/path/to/my_repo_2/my_module/.vscode/`

So I may be working on the same "repo" with 2 repos cloned on my local machine, with each repo checking out the same feature branch.

The current VS Code's "source control" would just show the same "git branch" on status bar, not of great help.
And this extension will always show "my_module" for both VS Code instances, still of no help.

So if there is an option to just show the "git folder" name, combining this with the built-in "source control"'s git branch name, it would be very easy to differentiate multiple VS Code instances.

Currently I have to click on the "Source control" side bar to check the "git folder name".

Thanks.

**Comment by koalamer** [comment]
If I understood correctly, you are working in two directories where the directory name is the same and therefore the extension displays the same name for both.
If so, simply use vscode's "save workspace as" command and save each with a different name, and then the extension will display what the resulting .vscode-vorkspace file was named, not the folder name, and then you can distinguish between the two.
